### ISSUE TITLE
[Guava] External markdown files

### ISSUE THREAD

**Issue by avandeursen** [delftswa2016/desosa2016#31]
Running gitbook on the Guava chapter gives two warnings:

    warn: page guava/chapter.md contains an hyperlink to resource outside spine './appendix-how_to_contribute.md' 
    warn: page guava/chapter.md contains an hyperlink to resource outside spine './appendix-our_contribution.md' 

I think you'd have to make up your mind whether you want to include this: If so, then you should probably concatenate the two files into your `chapter.md` files. 

The full contributions.md file may be a bit much to add: just pointing to the best pull requests might be enough?

**Comment by avandeursen** [comment]
As soon as your pull request is there we'll merge it in!

**Comment by mardibiase** [comment]
https://github.com/delftswa2016/desosa2016/pull/44

sorry for the *extreme* delay
