### ISSUE TITLE
[Opentripplanner] External Markdown Files

### ISSUE THREAD

**Issue by avandeursen** [delftswa2016/desosa2016#32]
Running gitbook on the Opentripplanner chapter gives a warning:

    warn: page opentripplanner/chapter.md contains an hyperlink to resource outside spine 'Appendix.Plannerstack.md'

If you want to include the text of the appendix, you'd have to include in your `chapter.md`.

**Comment by JoopAue** [comment]
@mvandertuin @ergone @thomhubers @acroockewit
